---
version: '3'
services:
  arangodb:
    image: arangodb:${ARANGO_DB_VERSION}
    restart: always
    ports:
      - ${ARANGO_DB_PORT}:8529
    network_mode: "bridge"
    environment:
      ARANGO_NO_AUTH: 1

  spline:
    image: absaoss/spline-rest-server:${SPLINE_CORE_VERSION}
    restart: always
    ports:
      - ${SPLINE_REST_PORT}:8080
    network_mode: "bridge"
    command: >
      bash -c "
        until curl --output /dev/null --silent --get --fail http://172.17.0.1:${ARANGO_DB_PORT}/_admin/server/availability
        do
          echo waiting for arango db
          sleep 5
        done
        echo downloading admin-cli &&
        curl -O -s https://repo1.maven.org/maven2/za/co/absa/spline/admin/${SPLINE_CORE_VERSION}/admin-${SPLINE_CORE_VERSION}.jar &&
        echo creating Spline database &&
        java -jar ./admin-${SPLINE_CORE_VERSION}.jar db-init arangodb://172.17.0.1:${ARANGO_DB_PORT}/spline -s &&
        echo starting Spline server &&
        catalina.sh run
      "
    environment:
      SPLINE_DATABASE_CONNECTION_URL: 'arangodb://172.17.0.1:${ARANGO_DB_PORT}/spline'
      # by default /dev/random is used which may block
      CATALINA_OPTS: "-Dsecurerandom.source=file:/dev/./urandom -Djava.security.egd=file:/dev/./urandom"
    links:
      - arangodb

  agent:
    image: absaoss/spline-spark-agent:${SPLINE_AGENT_VERSION}
    network_mode: "bridge"
    command: >
      bash -c "
        until curl --output /dev/null --silent --get --fail http://172.17.0.1:${SPLINE_REST_PORT}
        do
          echo waiting for spline
          sleep 5
        done
        mvn test -P examples \
          -D spline.producer.url=$${SPLINE_PRODUCER_URL} \
          -D spline.mode=$${SPLINE_MODE} \
          -D http.proxyHost=$${HTTP_PROXY_HOST} \
          -D http.proxyPort=$${HTTP_PROXY_PORT} \
          -D http.nonProxyHosts=$${HTTP_NON_PROXY_HOSTS}
      "
    environment:
      SPLINE_PRODUCER_URL: 'http://172.17.0.1:${SPLINE_REST_PORT}/producer'
    links:
      - spline

  ui:
    image: absaoss/spline-web-ui:${SPLINE_UI_VERSION}
    restart: always
    environment:
      # The consumer URL is used by the web browser
      SPLINE_CONSUMER_URL: 'http://${DOCKER_HOST_EXTERNAL:-localhost}:${SPLINE_REST_PORT}/consumer'
      # by default /dev/random is used which may block
      CATALINA_OPTS: "-Dsecurerandom.source=file:/dev/./urandom -Djava.security.egd=file:/dev/./urandom"
    ports:
      - ${SPLINE_UI_PORT}:8080
    links:
      - spline

