apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Release.Name }}
  ports:
  - protocol: {{ .Values.service.portType }}
    port: {{ .Values.service.port }}
